import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { ResourceModule } from "@kiritan/runtime";
import type { KiritanConfig } from "../config/types.js";
import { aggregateResources } from "../i18n/aggregate.js";
import { resolveNamespace } from "../i18n/namespace.js";

export interface TypegenOptions {
  cwd?: string;
}

export interface TypegenResult {
  /** Where the merged runtime data was written, relative to `cwd`. */
  dataPath: string;
  /** Where its type declaration was written, relative to `cwd`. */
  typesPath: string;
  /** How many `"<namespace>.<key>"` entries were written. */
  keyCount: number;
}

const DEFAULT_TYPEGEN_OUTPUT = "kiritan.runtime";

function renderDataModule(merged: ResourceModule): string {
  return [
    "// Auto-generated by `kiritan typegen`. Do not edit by hand.",
    `export const resources = ${JSON.stringify(merged, null, 2)};`,
    "",
  ].join("\n");
}

function renderTypesModule(merged: ResourceModule): string {
  const entries = Object.entries(merged).map(([key, localeMap]) => {
    const localeFields = Object.keys(localeMap)
      .map((locale) => `${JSON.stringify(locale)}: string;`)
      .join(" ");
    return `  ${JSON.stringify(key)}: { ${localeFields} };`;
  });
  return [
    "// Auto-generated by `kiritan typegen`. Do not edit by hand.",
    "export declare const resources: {",
    ...entries,
    "};",
    "",
  ].join("\n");
}

/**
 * `kiritan typegen` (docs/DESIGN.md 9.6章): merges every `runtime.sources` entry into one `ResourceModule` keyed by `"<namespace>.<key>"` (the namespace is derived from each file's path, or `ResourceSourceConfig.namespace` when set), then writes it out as a runtime data file plus a `.d.ts` declaring its exact shape.
 * This is only needed when aggregating multiple files into a single `createT()` call — a directly imported single file already gets full type inference for free (docs/DESIGN.md 9.2/9.5章).
 * If two resources resolve to the same `"<namespace>.<key>"`, the later one (in `runtime.sources` discovery order) silently wins.
 */
export async function typegen(
  config: KiritanConfig,
  options: TypegenOptions = {}
): Promise<TypegenResult> {
  const cwd = options.cwd ?? process.cwd();
  const sources = config.runtime?.sources ?? [];
  const aggregated = await aggregateResources(
    sources,
    config.locales.list,
    cwd
  );

  const merged: ResourceModule = {};
  for (const entry of aggregated) {
    const namespace = resolveNamespace(entry);
    for (const [key, localeMap] of Object.entries(entry.resource)) {
      merged[`${namespace}.${key}`] = localeMap;
    }
  }

  const outputBase = config.runtime?.typegenOutput ?? DEFAULT_TYPEGEN_OUTPUT;
  const dataPath = `${outputBase}.mjs`;
  const typesPath = `${outputBase}.d.ts`;

  await writeFile(join(cwd, dataPath), renderDataModule(merged), "utf8");
  await writeFile(join(cwd, typesPath), renderTypesModule(merged), "utf8");

  return { dataPath, typesPath, keyCount: Object.keys(merged).length };
}
